# Generated by Django 4.2.5 on 2023-10-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_autor_delete_informacionagregada'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcercaDeMi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
