# Generated by Django 4.2.5 on 2023-10-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_acercademi_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acercademi',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
