# Generated by Django 4.2.5 on 2023-10-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_alter_acercademi_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acercademi',
            name='nombre',
        ),
        migrations.AddField(
            model_name='acercademi',
            name='autor',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='acercademi',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='acercademi',
            name='subtitulo',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='acercademi',
            name='tiutlo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='acercademi',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
