# Generated by Django 4.2.5 on 2023-10-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_remove_acercademi_nombre_acercademi_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acercademi',
            old_name='tiutlo',
            new_name='titulo',
        ),
    ]
